---
:hierarchy:
  - "hosts/%{::fqdn}"
  - "roles/%{::hostname}"
  - "domains/%{::domain}"
  - project
  - common

:backends:
  - yaml
  - json

:json: &data_dir
  :datadir: "%{::hiera_config}/"

:yaml: *data_dir
